### ISSUE TITLE
Comparison with triton-included flash attention2

### ISSUE THREAD

**Issue by hypnopump** [FlagOpen/FlagAttention#4]
Hi there, nice work ;)!

I was wondering if you have benchmarked your implementation of Flash Attention 2 [against the one included in the triton library ](https://github.com/openai/triton/blob/main/python/triton/ops/flash_attention.py) which seems to use a single kernel in the backward pass and includes sequence parallelism. I have noticed you mention the split of kv and q kernels in the backward to have improved speed by 4-5x, and was just curious of the comparison.

**Comment by hypnopump** [comment]
[This blog post](https://zhuanlan.zhihu.com/p/665170554) explains briefly the sequence parallelism

**Comment by iclementine** [comment]
Yes. I've tested aginst the implementation in `triton.ops`, which is more stable, comparing with the frequently changing implementation is triton tutorials.

As I was implementing flash attention backward operator, I noticed that there are at least 5 implementations:

1. **Nested loop**: loop over the srquence length of both q and k in one CTA. This is the implementation in FlashAttention v1;
2. **Atomic gQ**: Update gradient of Q with AtomicAdd. This is the implementation in FlashAttention v2(cuda), and also in the paper of FlashAttention v2;
3. *multiple gQ*: mantain several replica of `gQ`(graident of Q) and apply a final reduce_sum. This is the implementation in triton.ops, which is referred to as `SEQUENCE_PARALLEL`. This is different from the **Atomic gQ** method. This method requires n(O^2) memory in backward operator;
4. **Split Q/KV kernels**: Split the backward into two kernels, one the calculate the gradient of Q and the other to compute the gradient of `K/V`. Althoght this two kernels can be launched concurrently in different streams, the number of available `SM`s may actually make them run sequentially;
5. **Concat Q/KV Kernels**: make a large grid with half of the CTAs computing gradient of Q, and the other half of CTAs computing the gradient of K/V. This was implemented in triton tutorial in some earlier commits. This also avoids atomic_add;
6. *Merge Q/KV Kernels*: merge the computation of Q and K/V  into one CTA. But this implementation requires some other conditions like the `num_blocks_m` equals `num_blocks_n` and `seqlen_m` equals `seqlen_m`.


I would post the benchmark results here including triton.ops.

# no sequence_paralle in triton.ops implementation (Nested Loop)

![attention_d-64_mode-fwd_causal-False_dtype-torch bfloat16](https://github.com/FlagOpen/FlagAttention/assets/16222986/18d4758e-8faa-4a96-a8dc-1cd60c4911d0)
![attention_d-64_mode-fwd_causal-False_dtype-torch float16](https://github.com/FlagOpen/FlagAttention/assets/16222986/f0a46b8d-919d-4242-ad8f-325248bc0c3c)
![attention_d-64_mode-fwd_causal-True_dtype-torch bfloat16](https://github.com/FlagOpen/FlagAttention/assets/16222986/55b9fc9a-7889-483a-8001-58e1c52c869e)
![attention_d-64_mode-fwd_causal-True_dtype-torch float16](https://github.com/FlagOpen/FlagAttention/assets/16222986/8f1a2389-87ff-4594-b677-92f5a0029264)

![attention_d-64_mode-bwd_causal-False_dtype-torch bfloat16](https://github.com/FlagOpen/FlagAttention/assets/16222986/5bae25b1-989a-4765-83ce-01eb613aea12)
![attention_d-64_mode-bwd_causal-False_dtype-torch float16](https://github.com/FlagOpen/FlagAttention/assets/16222986/21e9608f-d0d2-4b5c-ad80-8be9574f2524)
![attention_d-64_mode-bwd_causal-True_dtype-torch bfloat16](https://github.com/FlagOpen/FlagAttention/assets/16222986/1446447f-2f37-4539-846c-97f7975bab26)
![attention_d-64_mode-bwd_causal-True_dtype-torch float16](https://github.com/FlagOpen/FlagAttention/assets/16222986/29fc6a71-ae0f-4132-9f40-d3f2f6d53f04)

---

![attention_d-128_mode-fwd_causal-False_dtype-torch bfloat16](https://github.com/FlagOpen/FlagAttention/assets/16222986/1d63d23d-0f28-41df-9918-ca3ec48ad1a0)
![attention_d-128_mode-fwd_causal-False_dtype-torch float16](https://github.com/FlagOpen/FlagAttention/assets/16222986/8f21c1d3-e820-484f-aa9c-3a6f6e91bfca)
![attention_d-128_mode-fwd_causal-True_dtype-torch bfloat16](https://github.com/FlagOpen/FlagAttention/assets/16222986/25c398ba-252f-4434-ab21-21160dba0080)
![attention_d-128_mode-fwd_causal-True_dtype-torch float16](https://github.com/FlagOpen/FlagAttention/assets/16222986/72c03028-06ca-4d32-8947-e8a1c3d17d97)

![attention_d-128_mode-bwd_causal-False_dtype-torch bfloat16](https://github.com/FlagOpen/FlagAttention/assets/16222986/f283073c-7e25-43da-b20b-a35c56a605f5)
![attention_d-128_mode-bwd_causal-False_dtype-torch float16](https://github.com/FlagOpen/FlagAttention/assets/16222986/9b187fa7-683c-4dd3-8f3e-8344f6f9ab56)
![attention_d-128_mode-bwd_causal-True_dtype-torch bfloat16](https://github.com/FlagOpen/FlagAttention/assets/16222986/e28fa19d-0ab4-4fb2-819a-80ba4a6684f5)
![attention_d-128_mode-bwd_causal-True_dtype-torch float16](https://github.com/FlagOpen/FlagAttention/assets/16222986/5dcb8923-d8ce-44ef-96e3-16e6243856e6)

#  sequence_paralle in triton.ops implementation(Mtltiple gQ)

![attention_d-64_mode-fwd_causal-False_dtype-torch bfloat16](https://github.com/FlagOpen/FlagAttention/assets/16222986/f44d5f91-36f1-4a08-a9c0-8fb53752e58b)
![attention_d-64_mode-fwd_causal-False_dtype-torch float16](https://github.com/FlagOpen/FlagAttention/assets/16222986/4d26e68b-e394-41cf-822d-00478328361f)
![attention_d-64_mode-fwd_causal-True_dtype-torch bfloat16](https://github.com/FlagOpen/FlagAttention/assets/16222986/81637ad7-0c68-419e-944d-d10f24b7c2aa)
![attention_d-64_mode-fwd_causal-True_dtype-torch float16](https://github.com/FlagOpen/FlagAttention/assets/16222986/329b98bb-400c-4744-93c1-8dc870feba35)


![attention_d-64_mode-bwd_causal-False_dtype-torch bfloat16](https://github.com/FlagOpen/FlagAttention/assets/16222986/b5afed00-fd64-45cf-abdf-60d0748ac9b2)
![attention_d-64_mode-bwd_causal-False_dtype-torch float16](https://github.com/FlagOpen/FlagAttention/assets/16222986/f011ab63-3dc7-4d1b-b8fe-488d71a5a912)
![attention_d-64_mode-bwd_causal-True_dtype-torch bfloat16](https://github.com/FlagOpen/FlagAttention/assets/16222986/49542a5f-be7e-4ac3-bb7b-fed333e2f429)
![attention_d-64_mode-bwd_causal-True_dtype-torch float16](https://github.com/FlagOpen/FlagAttention/assets/16222986/2cc4f3f6-7852-4362-8eb9-752a9a9ca49b)

---

![attention_d-128_mode-fwd_causal-False_dtype-torch bfloat16](https://github.com/FlagOpen/FlagAttention/assets/16222986/1c28814d-60aa-4c69-9876-11b0883bee6c)
![attention_d-128_mode-fwd_causal-False_dtype-torch float16](https://github.com/FlagOpen/FlagAttention/assets/16222986/ca02bf48-9647-4d18-868b-47e17a2bd6f3)
![attention_d-128_mode-fwd_causal-True_dtype-torch bfloat16](https://github.com/FlagOpen/FlagAttention/assets/16222986/1281a3f8-3fab-4038-a47b-02124dbc3827)
![attention_d-128_mode-fwd_causal-True_dtype-torch float16](https://github.com/FlagOpen/FlagAttention/assets/16222986/06a5a90b-125a-49ac-919e-844d31a36b2a)

![attention_d-128_mode-bwd_causal-False_dtype-torch bfloat16](https://github.com/FlagOpen/FlagAttention/assets/16222986/40a7e707-524d-4e21-b465-5e123ca9e603)
![attention_d-128_mode-bwd_causal-False_dtype-torch float16](https://github.com/FlagOpen/FlagAttention/assets/16222986/756bdcd4-633e-4b09-a741-3e0a08970466)
![attention_d-128_mode-bwd_causal-True_dtype-torch bfloat16](https://github.com/FlagOpen/FlagAttention/assets/16222986/fb0a230a-24e1-46a5-b22e-64c18a543e96)
![attention_d-128_mode-bwd_causal-True_dtype-torch float16](https://github.com/FlagOpen/FlagAttention/assets/16222986/8fafc6fe-a9fb-48fd-8694-efdc431182f4)

**Comment by SonicZun** [comment]
Thanks for your amazing work!
In the latest version of Triton's official tutorial, when directly running the Flash Attention 2 Python script (head dim is 64), Triton's implementation is faster than the official Flash Attention library in both forward and backward passes. However, when the head dimension is changed to 128, it becomes significantly slower than the official Flash Attention library. Do you know what might be causing this?
